### PR TITLE
Clarify how to use ascii character classes in [..]

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
See also https://github.com/rust-lang-nursery/regex/issues/287 :)

**Comment by BurntSushi** [comment]
This is actually related to #175. If we merge this, I'd guess we are committing to this syntax. Which doesn't seem that bad.

**Comment by matklad** [comment]
Hm, if `[:alpha:]` is not a character class by itself, then there is no confusion at all. So looks like changing `[:alpha:]` to `[[:alpha:]]` would be a more fundamental fix for the problem.

**Comment by BurntSushi** [comment]
@matklad I'm going to fix #175 instead, so I think we can close this. Thanks anyway!

**Pull request closed without merging**
