### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by Manishearth**
cc @BurntSushi 

new PR to retrigger appveyor

### CODE REVIEW

**Comment by Manishearth** [comment]
Okay, I think something's wrong with the CI?

@alexcrichton could you look into this? This crate has a lot of reverse dependencies and is currently broken on nightly; this PR fixes it but doesn't pass appveyor with strange link issues.

**Comment by alexcrichton** [comment]
windows nightlies are unfortunately just broken right now

**Comment by BurntSushi** [comment]
All right, then I'll just merge this for now and update in the interest of unbreaking folks.

**Comment by BurntSushi** [comment]
Thanks @Manishearth! crates.io update incoming...

**Comment by BurntSushi** [comment]
`regex_macros 0.1.22` is on crates.io.

**Pull request merged**
