### PR TITLE
Refactor internal API to remove constant overhead.

### LINKED ISSUE #192: avoid excessive cache retrieval for find_iter and captures_iter
Commit 31a317eadd7d0270dea4ac90b54f5f560514ed01 introduced a faster memory pool based on spin locks (see #188), which have slightly less overhead than mutexes for our use case (very little contention). This provided a nice perf boost to regexes that match on short haystacks or for regexes that match a lot in a large haystack. Stated differently, it reduced the constant overhead of matching a regex.

We should be able to do quite a bit better. At the moment, when `find_iter`/`captures_iter` executes, it fetches a regex cache on every single search. At a high level, it should be able to hang on to the cache for the duration of the iteration (say, until `FindMatches` is dropped).

Actually doing this proved quite tricky because of how the logic is divided internally. For example, code in `re_unicode.rs` needs to know *not* to retrieve a cache if one is never needed (e.g., literal-only search). It also needs to thread the cache through the entire internal API, which isn't very fun.

In any case, this should be quite a nice win if implemented right.

### PR DESCRIPTION
**Pull request by BurntSushi**
This commit contains three classes of improvements that are all
motivated by reducing constant overhead of matching by as much as
possible:

  1. Reduce the number of state loads per iteration of the DFA loop from
     2 to 1.
  2. Use `inline(always)` to reduce the number of function calls made
     between a public API call and the inner DFA loop.
  3. Push more case analysis from match-time to compile-time. We can now
     start searching with only 1 or 2 branches.

There are more `inline(always)` annotations than I'm comfortable with,
but I have actually benchmarked all (or most, I think) of them. Many of
them can result in a 10-25% performance boost, and generally
significantly reduces the number of instructions that need to be run
per-match. This does make `cargo build --release` a few seconds longer.
Despite all of that, I personally think it's awesome that we're at a
point where function inlining impacts search performance this
dramatically!

Other improvements:

  1. There is now an *internal* trait, RegularExpression, that organizes
     the internal API a bit more. Notably, it allows us to get rid of
     duplicate implementations of `find_iter` and `captures_iter`.
  2. The old `Params`-based internal API is gone. Its design moved too
     much case analysis to match-time. We've replaced it with more
     explicit implementations for each type of search, rather than
     trying to dynamically reconfigure ourselves.
  3. All iterators now amortize the overhead of the TLS fetch for the
     cache. This isn't really a big deal in the single threaded case
     (approximate 1ns of overhead per match on Linux), but should reduce
     contention quite a bit in the multi-threaded case. This does mean
     that the iterator types (`FindMatches` and `FindCaptures`) no longer
     satisfy `Sync`. I suspect this is fine since I can't imagine any
     productive use of `Sync` on these iterators anyway (their only public
     methods take `&mut self`).
  4. Anchored regexes with complete literals now have their own matching
     paths, which makes obvious cases like `^foo` or `foo$` execute
     exactly as fast as you might imagine.

Fixes #192.

### CODE REVIEW

**Comment by BurntSushi** [comment]
Lots of perf improvements across the board!

```
[andrew@Liger regex] cargo-benchcmp ~/rust/regex-master/master-rust less-overhead-rust --threshold 5
name                                     master-rust ns/iter   rust.5 ns/iter          diff ns/iter   diff %
misc::anchored_literal_long_match        43 (9,069 MB/s)       35 (11,142 MB/s)                  -8  -18.60%
misc::anchored_literal_long_non_match    13 (30,000 MB/s)      16 (24,375 MB/s)                   3   23.08%
misc::anchored_literal_short_match       40 (650 MB/s)         34 (764 MB/s)                     -6  -15.00%
misc::anchored_literal_short_non_match   20 (1,300 MB/s)       16 (1,625 MB/s)                   -4  -20.00%
misc::easy0_1K                           230 (4,569 MB/s)      29 (36,241 MB/s)                -201  -87.39%
misc::easy0_1MB                          38,876 (26,973 MB/s)  43 (24,386,116 MB/s)         -38,833  -99.89%
misc::easy0_32                           179 (329 MB/s)        29 (2,034 MB/s)                 -150  -83.80%
misc::easy0_32K                          985 (33,294 MB/s)     29 (1,130,862 MB/s)             -956  -97.06%
misc::easy1_1K                           233 (4,480 MB/s)      171 (6,105 MB/s)                 -62  -26.61%
misc::hard_1K                            215 (4,888 MB/s)      198 (5,308 MB/s)                 -17   -7.91%
misc::literal                            18 (2,833 MB/s)       17 (3,000 MB/s)                   -1   -5.56%
misc::match_class_unicode                752 (214 MB/s)        710 (226 MB/s)                   -42   -5.59%
misc::medium_1K                          227 (4,634 MB/s)      30 (35,066 MB/s)                -197  -86.78%
misc::medium_1MB                         38,735 (27,071 MB/s)  45 (23,302,311 MB/s)         -38,690  -99.88%
misc::medium_32                          174 (344 MB/s)        30 (2,000 MB/s)                 -144  -82.76%
misc::medium_32K                         997 (32,894 MB/s)     30 (1,093,200 MB/s)             -967  -96.99%
misc::not_literal                        256 (199 MB/s)        243 (209 MB/s)                   -13   -5.08%
misc::one_pass_long_prefix               146 (178 MB/s)        134 (194 MB/s)                   -12   -8.22%
misc::one_pass_long_prefix_not           143 (181 MB/s)        133 (195 MB/s)                   -10   -6.99%
misc::one_pass_short                     104 (163 MB/s)        96 (177 MB/s)                     -8   -7.69%
misc::one_pass_short_not                 102 (166 MB/s)        94 (180 MB/s)                     -8   -7.84%
misc::reallyhard_1K                      4,776 (220 MB/s)      4,496 (233 MB/s)                -280   -5.86%
misc::reallyhard_1MB                     4,825,198 (217 MB/s)  4,470,343 (234 MB/s)        -354,855   -7.35%
misc::reallyhard_32                      292 (202 MB/s)        277 (212 MB/s)                   -15   -5.14%
misc::reallyhard_32K                     148,205 (221 MB/s)    140,233 (233 MB/s)            -7,972   -5.38%
misc::replace_all                        158                   137                              -21  -13.29%
rust_compile::compile_huge_full          31,423,822            38,817,390                 7,393,568   23.53%
sherlock::before_holmes                  109,585 (5,428 MB/s)  103,741 (5,734 MB/s)          -5,844   -5.33%
sherlock::everything_greedy              6,957,753 (85 MB/s)   6,270,022 (94 MB/s)         -687,731   -9.88%
sherlock::everything_greedy_nl           5,815,332 (102 MB/s)  5,282,166 (112 MB/s)        -533,166   -9.17%
sherlock::holmes_coword_watson           1,312,553 (453 MB/s)  1,239,639 (479 MB/s)         -72,914   -5.56%
sherlock::ing_suffix_limited_space       2,929,990 (203 MB/s)  2,736,077 (217 MB/s)        -193,913   -6.62%
sherlock::letters                        28,319,208 (21 MB/s)  23,563,986 (25 MB/s)      -4,755,222  -16.79%
sherlock::letters_lower                  28,098,651 (21 MB/s)  23,178,178 (25 MB/s)      -4,920,473  -17.51%
sherlock::letters_upper                  3,582,304 (166 MB/s)  3,297,624 (180 MB/s)        -284,680   -7.95%
sherlock::line_boundary_sherlock_holmes  2,701,415 (220 MB/s)  2,526,994 (235 MB/s)        -174,421   -6.46%
sherlock::name_alt1                      38,492 (15,456 MB/s)  36,495 (16,301 MB/s)          -1,997   -5.19%
sherlock::name_holmes                    51,285 (11,600 MB/s)  43,200 (13,771 MB/s)          -8,085  -15.76%
sherlock::name_sherlock_holmes           39,278 (15,146 MB/s)  37,236 (15,977 MB/s)          -2,042   -5.20%
sherlock::repeated_class_negation        81,851,914 (7 MB/s)   89,471,005 (6 MB/s)        7,619,091    9.31%
sherlock::the_lower                      680,019 (874 MB/s)    605,254 (982 MB/s)           -74,765  -10.99%
sherlock::the_upper                      55,637 (10,693 MB/s)  45,344 (13,120 MB/s)         -10,293  -18.50%
sherlock::the_whitespace                 1,478,237 (402 MB/s)  1,357,908 (438 MB/s)        -120,329   -8.14%
sherlock::words                          11,918,051 (49 MB/s)  10,242,156 (58 MB/s)      -1,675,895  -14.06%
```

**Comment by BurntSushi** [comment]
We now compare much more favorably with PCRE, which is quite good with low overhead matching on short haystacks:

```
$ cargo-benchcmp pcre rust.5 --threshold 5 --regressions
name                                     pcre ns/iter          rust.5 ns/iter          diff ns/iter    diff %
misc::long_needle2                       533,695 (187 MB/s)    683,525 (146 MB/s)           149,830    28.07%
misc::match_class_unicode                516 (312 MB/s)        710 (226 MB/s)                   194    37.60%
misc::one_pass_long_prefix               87 (298 MB/s)         134 (194 MB/s)                    47    54.02%
misc::one_pass_long_prefix_not           87 (298 MB/s)         133 (195 MB/s)                    46    52.87%
sherlock::line_boundary_sherlock_holmes  194,118 (3,064 MB/s)  2,526,994 (235 MB/s)       2,332,876  1201.78%
sherlock::name_alt3                      1,087,781 (546 MB/s)  1,250,241 (475 MB/s)         162,460    14.93%
sherlock::name_holmes_nocase             495,558 (1,200 MB/s)  1,085,787 (547 MB/s)         590,229   119.10%
sherlock::repeated_class_negation        7,247,648 (82 MB/s)   89,471,005 (6 MB/s)       82,223,357  1134.48%
sherlock::the_nocase                     1,276,264 (466 MB/s)  1,580,462 (376 MB/s)         304,198    23.84%
sherlock::word_ending_n                  11,856,744 (50 MB/s)  57,436,723 (10 MB/s)      45,579,979   384.42%
```

And Oniguruma:

```
cargo-benchcmp onig rust.5 --threshold 5 --regressions
name                                     onig ns/iter          rust.5 ns/iter          diff ns/iter    diff %
misc::one_pass_long_prefix               92 (282 MB/s)         134 (194 MB/s)                    42    45.65%
misc::one_pass_long_prefix_not           96 (270 MB/s)         133 (195 MB/s)                    37    38.54%
sherlock::everything_greedy              5,151,927 (115 MB/s)  6,270,022 (94 MB/s)        1,118,095    21.70%
sherlock::line_boundary_sherlock_holmes  195,745 (3,039 MB/s)  2,526,994 (235 MB/s)       2,331,249  1190.96%
sherlock::repeated_class_negation        43,439,285 (13 MB/s)  89,471,005 (6 MB/s)       46,031,720   105.97%
sherlock::word_ending_n                  27,925,793 (21 MB/s)  57,436,723 (10 MB/s)      29,510,930   105.68%
```

Some of the remaining benchmarks for PCRE should hopefully get fixed with @shepmaster's `jetscii` crate. :-)

**Comment by shepmaster** [comment]
> jetscii crate. :-)

Not too much pressure, eh! :-)

Congratulations on your speedups; keep up the amazing work!

**Comment by alexcrichton** [comment]
*swoon*

Nice! Some of those improvements (like 27,071 MB/s to 23,302,311 MB/s) are insane.

Out of curiosity, did you play much with `#[inline]` vs `#[inline(always)]`? 

r=me in any case when this is ready!

**Comment by BurntSushi** [comment]
@alexcrichton I did play with `#[inline]` vs. `#[inline(always)]` and the former never seemed to get them to inline. They are pretty big functions so I'm not totally surprised then it requires a hammer. I did remove a few `inline(always)` annotations, particularly around the slow paths.

Also, some of those benchmark improvement are because of specialty optimizations. e.g., a regex like `foobar$` will match at the same speed on 1MB of text as it will on 1KB of text. It seems like an obvious optimization, but it wasn't there before! (As a result, many of the `misc` benchmarks are now kind of broken. They'll be rewritten/reorganized in time. :-))

**Comment by alexcrichton** [comment]
Makes sense to me, and sounds good all around!

**Comment by BurntSushi** [comment]
This PR is in `regex 0.1.63`.

**Comment by bstrie** [comment]
Holy wow! Great improvements. :)

**Pull request merged**
