### PR TITLE
Fix regex_macros

### LINKED ISSUE #181: regex_macros is broken
`Inst::Match` was given a new field, and now the crate doesn't compile on master.

```
$ cargo build
   Compiling regex_macros v0.1.31 (file:///home/manishearth/Mozilla/Git/regex/regex_macros)
src/lib.rs:437:17: 437:28 error: this pattern has 0 fields, but the corresponding variant has 1 field [E0023]
src/lib.rs:437                 Inst::Match => quote_expr!(self.cx, {
                               ^~~~~~~~~~~
src/lib.rs:437:17: 437:28 help: run `rustc --explain E0023` to see a detailed explanation
error: aborting due to previous error
Could not compile `regex_macros`.
```

(shouldn't the CI catch this?)

### PR DESCRIPTION
**Pull request by mcarton**
Fix #181.

### CODE REVIEW

**Comment by BurntSushi** [comment]
Thanks!

**Comment by BurntSushi** [comment]
Published on crates.io in `0.1.32`.

**Comment by mcarton** [comment]
Thanks!

**Comment by tinyplasticgreyknight** [comment]
:+1: Now I can progress :-)

**Comment by BurntSushi** [comment]
@tinyplasticgreyknight FYI, `regex!` is quite a bit slower than using `Regex::new` these days. Unless you have very specialized needs, I'd recommend going with `Regex::new`.

**Comment by tinyplasticgreyknight** [comment]
Thanks, but it's actually a transitive dependency of something else I am trying to compile. :-)  Now successfully!

**Pull request merged**
