### PR TITLE
Rust upgrade to rustc 1.7.0-nightly (d70ab2bdf)

### LINKED ISSUE #147: Can't compile on rustc 1.7.0-dev (2016-01-08)
regex_macros-0.1.25/src/lib.rs:555:37: 555:41 error: no method named `ok` found for type `bool` in the current scope
    regex_macros-0.1.25/src/lib.rs:555         if !parser.eat(&token::Eof).ok().unwrap() {

### PR DESCRIPTION
**Pull request by mcarton**
multirust now has *rustc 1.7.0-nightly (d70ab2bdf 2016-01-08)*.
Fix #147.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

**Comment by mcarton** [comment]
Can a new version be published?
Clippy does not build because of this on the last nightly & Travis.

**Comment by BurntSushi** [comment]
@mcarton Ah sorry about that! It's published now. Thanks!

**Comment by mcarton** [comment]
Thanks!

**Pull request merged**
