### PR TITLE
Bump thread_local version and test on Rust 1.3.

### LINKED ISSUE #206: 0.1.66 breaks semver
0.1.66 includes cdee1e7, which introduces a **breaking change**.  Existing code that compiles under Rust 1.3.0-1.5.0 stops compiling due to the transitive dependency on `void`.

### PR DESCRIPTION
**Pull request by BurntSushi**
Fixes #206.

### CODE REVIEW

**Comment by Amanieu** [comment]
I don't think bumping the version number is necessary since Cargo will automatically pick up the new version.

**Comment by BurntSushi** [comment]
I think it's necessary to specify a minimum bound, otherwise it's not *guaranteed* that Cargo will pick up the new version? (e.g., If there's some other constraint on the version of `thread_local` in a build.) I might be misunderstanding though.

**Comment by alexcrichton** [comment]
Yeah this way regex say it's *only* compatible with 0.2.4 and above (which I believe is the correct case)

**Comment by BurntSushi** [comment]
@alexcrichton So, I hadn't merged this yet because I don't think it will build on Rust 1.3 on Windows. :P So I guess we technically support Rust 1.3+ on Linux and Rust 1.4+ on Windows.

**Comment by alexcrichton** [comment]
Gah oops! Sorry about that :(

Out of curiosity, is there one place these version dependencies are coming from? Or are they just for convenience?

**Comment by BurntSushi** [comment]
@alexcrichton I think I'm just sympathetic to the "your build just broke because a semver bump required a newer Rust." I don't think we have any policy on it yet, but maybe it's time to talk about it? :-)

**Comment by alexcrichton** [comment]
Yeah seems fine to me, I'll add an item to our agenda.

**Pull request merged**
