### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by BurntSushi** [comment]
Hmm, I have no idea what's going on with Windows there...

**Comment by Manishearth** [comment]
It passed on the last push

**Comment by BurntSushi** [comment]
@Manishearth Looks like it's still failing? https://ci.appveyor.com/project/alexcrichton/regex/build/1.0.222/job/ar58x1lf8d15tm6s I'm not sure if it's actually related to this change though.

(This looks great though! Thank you. :-))

**Comment by Manishearth** [comment]
You'll need to manually retrigger appveyor I guess.

**Pull request closed without merging**
